# Generated by Django 5.2 on 2025-05-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coocking_time',
            new_name='cooking_time',
        ),
    ]
