# Generated by Django 5.2 on 2025-05-20 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Имя пользователя может содержать только буквы, цифры и знаки @/./+/-/_",
                        regex="^[\\w.@+-]+$",
                    )
                ],
            ),
        ),
    ]
